app1/urls.py
from django.urls import path
from . import views
app_name='app1'
urlpatterns=[
    path('',views.index,),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('home/<int:id>',views.home,name='home'),
    path('update/<int:id>',views.update,name='update'),
	path('logout',views.logout,name='logout'),
    path('gallery',views.gallery,name='gallery'),
    path('imgdetails/<int:id>',views.imgdetails,name='imgdetails'),
    

]

newproject1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models

# Create your models here.
class Signup(models.Model):
	Name=models.CharField(max_length=10)
	Age=models.IntegerField()
	Place=models.CharField(max_length=20)
	Photo=models.ImageField(upload_to='media/',blank=True,null=True)
	Email=models.EmailField(max_length=18)
	Password=models.CharField(max_length=8)

class Gallery(models.Model):
	Photo=models.ImageField()
	Name=models.CharField(max_length=100)
	Price=models.CharField(max_length=100)
	Model=models.CharField(max_length=100)
	Details=models.CharField(max_length=1000)

app1/forms.py
from django import forms
from . models import Signup
class SignupForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8)
    class Meta():
        model=Signup
        fields='__all__'


class LoginForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8)
    class Meta():
        model=Signup
        fields=('Email','Password')


class UpdatForm(forms.ModelForm):
	class Meta():
		model=Signup
		fields=('Name','Age','Place','Photo','Email')

app1/views.py
from django.shortcuts import render,redirect
from . models import Signup,Gallery
from . forms import SignupForm,LoginForm,UpdatForm
from django.contrib import messages
from django.contrib.auth import logout as logouts
# Create your views here.
def index(request):
    return render(request,'index.html')

def register(request):
    if request.method =='POST':
        f=SignupForm(request.POST or None,request.FILES or None)
        if f.is_valid():
            name=f.cleaned_data['Name']
            age=f.cleaned_data['Age']
            place=f.cleaned_data['Place']
            photo=f.cleaned_data['Photo']
            email=f.cleaned_data['Email']
            password=f.cleaned_data['Password']
            user=Signup.objects.filter(Email=email).exists()
            if user:
                messages.warning(request,"email allready exist")
                return redirect('/register')
            else:
                tab=Signup(Name=name,Age=age,Place=place,Email=email,Password=password,Photo=photo) 
                tab.save()
                messages.success(request,'registration success')
                return redirect('/')
    else:
        f=SignupForm()
    return render(request,'register.html',{'form':f})  


def login(request):
    if request.method =='POST':
        f=LoginForm(request.POST)
        if f.is_valid():
            email=f.cleaned_data['Email']
            password=f.cleaned_data['Password']
            user=Signup.objects.get(Email=email)
            if not user:
                messages.warning(request,"user dosnot exists")
                return redirect('/login')
            elif user.Password != password:
                messages.warning(request,'password incorrect')
                return redirect('/login')
            else:
                return redirect('/home/%s'% user.id)      
    else:
        f=LoginForm()
    return render(request,'login.html',{'form':f})

def home(request,id):
    user=Signup.objects.get(id=id)
    return render(request,'home.html',{'user':user})

def update(request,id):
	user=Signup.objects.get(id=id)
	if request.method=='POST':
		f=UpdatForm(request.POST or None,request.FILES or None,instance=user)
		if f.is_valid():
			name=f.cleaned_data['Name']
			age=f.cleaned_data['Age']
			place=f.cleaned_data['Place']
			photo=f.cleaned_data['Photo']
			email=f.cleaned_data['Email']
			f.save()
			return redirect('/home/%s' % user.id)
	else:
		f=UpdatForm(instance=user)
	return render(request,'update.html',{'f':f,'user':user})	


def logout(request):
	logouts(request)
	messages.success(request,'logedout successfully')
	return redirect('/')


def gallery(request):
    details=Gallery.objects.all()
    return render(request,'gallery.html',{'data':details})
def imgdetails(request,id):
    data=Gallery.objects.get(id=id)
    return render(request,'imgdetails.html',{'data':data})

app1/templates/gallery.html
<html>
    {% load static %}
    <body>
        <div class="container" style="background-color: rgb(22, 23, 24); border: outset black ; margin-top: 50px;margin-left: 30px; margin-right:100px;margin-bottom: 20px;">
            {% for d in data %}
        <a href="{% url 'app1:imgdetails' d.id %}"><img src="{{ d.Photo.url }}" height="250px" width="250px" ></a>
        {% endfor %}

        </div>
        
    </body>
</html>

app1/templates/home.html
<html>
    <body>
    {{user.Name}}
    <img src="{{ user.Photo.url }}">
    </body>
</html>

app1/templates/imgdetails.html
<html>
    <head>
        <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      </head>
      <body style="background-color: rgb(218, 218, 233);">

        <div class="container" style="border:outset black; margin-top: 30px; background-color: whitesmoke;">
            {{data.id}}

            <img src="{{ data.Photo.url }}"><br><br>
            {{data.name}}<br>
            {{data.Price}}<br>
            {{data.Model}}<br>
            {{data.Details}}<br>
        </div>
    </body>

<html>
    

app1/templates/index.html
<html>
    <head>
        <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      </head>
<body  style="background-color: aqua;">
    <div class="container" >
        <div style="border: 1px outset brown; height: 400px; width: 300px; padding: 10px;background-color: rgb(235, 187, 126);margin-top: 80px;margin-left: 300px;">
            <a href="{% url 'app1:register' %}"><button class="btn btn-success">Signup</button> </a><br><br><br>
        <a href="{% url 'app1:login' %}"><button class="btn btn-success">Login</button></a><br><br><br>
        <a href="{% url 'app1:gallery' %}"><button class="btn btn-success">Gallery</button></a>
        </div>
        
    </div>
    
</body>
</html>

app1/templates/login.html
<html>
    <head>
        <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      </head>
      <body style="background-color: seagreen;">
        <div class="container" style="background-color:whitesmoke; width: 450;margin-top: 100px;">
            <form action="{% url 'app1:login' %}" method="POST">
                {% csrf_token %}
                <table>
                    <tr><td style="padding-bottom: 50px;">{{form.as_table}}</td></tr>
                </table><br><br>
                <input type="submit" name="btsub" value="login" class="btn btn-success">
    
            </form>
        </div>
       
    </body>
</html>
    
   

app1/templates/register.html
<html>
    <head>
        <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      </head>
    
        <body style="background-color: darkgreen;">
            <div class="container" style="background-color: whitesmoke; margin-top: 50px; margin-right: 45px;">
                <form action="{% url 'app1:register' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table style="margin-top: 50px;background-color: darkgrey; margin-bottom: 30px;">
                        <tr><td>{{form.as_table}}</td></tr>
                    </table>
                    <input type="submit" name="btsub" value="register" class="btn btn-success">
    
                </form>
            </div>
            


        </body>
</html>

app1/templates/update.html
<html>
    <body>
            <form action="{% url 'app1:update' user.id %}" method="POST">
                {% csrf_token %}
            <table>
                <tr><td>{{f.as_table}}</td></tr>
            </table>	
            <input type="submit" name="btsub" value="update">
            </form>
    
    </body>
</html>